### ISSUE TITLE
ClearType rendering issue in VS Code for Windows 10

### ISSUE THREAD

**Issue by richellyitalo** [thunderpoot/WumpusMono#1]
A great font. But when using it in my Vscode on Windows, I'm having some problems with pixels remaining.

Any solution for this?
![font-fix](https://github.com/vaughantype/wumpus-mono/assets/1899604/c81e97e8-7f49-4249-8bf5-77053533bf9e)

**Comment by thunderpoot** [comment]
Hi @richellyitalo, thanks! If you follow the suggestions in this Gist, does it solve the problem?

https://gist.github.com/hanksudo/33ddf24f27f403c00b746b6f12bde746

**Comment by thunderpoot** [comment]
I've had to spin up a virtual machine to test this – I don't see the aliasing visible in your screenshot!  The checkbox mentioned in the above Gist is enabled, and `--disable-gpu --enable-use-zoom-for-dsf` is appended to the Target in VS Code properties (although I actually can't see a difference with these enabled).

Can you confirm that this is Wumpus Mono version 1.027? Could you also share which version of Windows and which version of VS Code you're running?

<img width="603" alt="Screenshot 2023-09-10 at 19 41 55" src="https://github.com/vaughantype/wumpus-mono/assets/54200401/896555d5-6706-4b3a-a8ad-84f80408b544">

**Comment by richellyitalo** [comment]
Hi @thunderpoot 
Thanks for the links, but unfortunately it didn't work.
![params_vscode](https://github.com/vaughantype/wumpus-mono/assets/1899604/973f3294-ca4a-4bd5-b07c-e7f4a443351a)

Following information:
SO: Windows 10 PRO - 22h2 (Build 19045.3324)
Wumpus Mono (demo from this repo) 1.027
VSCode: 1.82.0

VSCode settings:
- Font Size: 12.5

- Font family: wumpus mono pro
- Zoom: 2
- Line height: 2

**Comment by thunderpoot** [comment]
Thanks for the extra info.  Can you share whether this is also happening in other software, or if it's just VS Code?

**Comment by richellyitalo** [comment]
Of course.
Follows the screenshot in notepad ++:
![npp](https://github.com/vaughantype/wumpus-mono/assets/1899604/a8b233d2-3142-468f-bdfe-73eaf532c0b2)

Looks like normal in this software.

**Comment by thunderpoot** [comment]
That is interesting. Thank you for the helpful info.

It looks like others have had the same problem with different font files in VS Code on Windows 10, see [this thread on Reddit.](https://www.reddit.com/r/vscode/comments/p976n3/many_fonts_look_ugly_in_vscode_windows_10_version/).

If it helps, it doesn't appear to be happening in VS Code in my virtual machine (running Windows 11).

It seems (from my understanding) that [ClearType](https://learn.microsoft.com/en-us/typography/cleartype/) is what is causing this, which was not a consideration when proofing/hinting Wumpus Mono.  I will make a note for future development, and perhaps the hinting for Wumpus Mono can be revisited.

In the meantime, you may find that it looks better using the variable TrueType font at a heavier weight (but this would require a Pro desktop licence).
